<?php

namespace App\Models\API\GMO\V1\Kurapital;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class DeletedOpportunity extends Model
{
    //
    protected $connection = 'gmoCrm';
    protected $table = 'app_deleted_opportunities';
	public $timestamps = false;
    // const CREATED_AT = 'created';
    // const UPDATED_AT = 'modified';

    protected $fillable = [
		'opportunity_id',
		'user_id',
		'datas',
		'deleted_date',
		// 'hash',
		// 'firstname',
		// 'familyname',
		// 'firstname_kana',
		// 'familyname_kana',
		// 'gender_id',
		// 'generation_id',
		// 'company_name',
		// 'prefecture',
		// 'city',
		// 'address',
		// 'phone1',
		// 'phone2',
		// 'fax',
		// 'trouble',
		// 'note',
		// 'negotiation',
		// 'cancel',
		// 'receipt_date',
		// 'work_date',
		// 'worked_date',
		// 'sales',
		// 'material_cost',
		// 'material_detail',
		// 'material_price',
		// 'highway_cost',
		// 'highway_from',
		// 'highway_to',
		// 'parking_cost',
		// 'stamp_cost',
		// 'partner_fee',
		// 'allowed_cost',
		// 'allowed_detail',
		// 'kurapital_fee',
		// 'other_cost',
		// 'kurapital_cost',
		// 'detail',
		// 'pay_by_invoice',
		// 'pay_by_service_paper',
		// 'payed_by_card',
		// 'field_id',
		// 'status_id',
		// 'account_id',
		// 'user_id',
		// 'owner_id',
		// 'is_additional_projects',
		// 'created',
		// 'modified',
		// 'incoming_phone',
		// 'cancel_reason_id',
		// 'work_content_id',
		// 'work_target_id',
		// 'proposal',
		// 'receipt_status_id',
		// 'bill_status_id',
		// 'opportunity_demand_status_id',
		// 'dial_id',
		// 'kaitori',
		// 'houzinflg',
		// 'seisanflg',
		// 'sub_category_id',
		// 'sendmail',
		// 'building_name',
		// 'shop_name',
		// 'is_completed',
		// 'shift_id',
		// 'mail_address',
		// 'requested_lat_lng',
		// 'last_update_from',
		// 'building_room',
		// 'not_urikake_flg',
		// 'other_bill_status_id',
		// 'is_time_designation',
		// 'is_reschedule',
		// 'is_claim',
		// 'is_company',
		// 'reception_number',
		// 'report_mail',
		// 'work_date_end',
		// 'is_construction',
		// 'order_amount',
		// 'order_date',
		// 'is_photo_registered',
		// 'personnel_name',
		// 'estimation_email_address',
		// 'photo_report_email_address',
		// 'is_free_time',
		// 'is_attendance',
		// 'is_accounting_confirmed',
		// 'accounting_confirmed_amount',
		// 'on_site_billing_type_id',
		// 'on_site_billing_method_id',
		// 'basic_research_fee',
		// 'budget_amount',
		// 'is_transfer',
	];
}
