<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('opportunities', function (Blueprint $table) {
            $table->id();
            $table->string('hash')->nullable()->index();
            $table->integer('field_id')->nullable()->index();
            $table->integer('dial_id')->nullable()->index();
            $table->string('firstname')->nullable()->index();
            $table->string('familyname')->nullable()->index();
            $table->string('firstname_kana')->nullable()->index();
            $table->string('familyname_kana')->nullable()->index();
            $table->integer('gender_id')->nullable()->index();
            $table->integer('generation_id')->nullable()->index();
            $table->string('mail_address')->nullable()->index();
            $table->string('report_mail')->nullable()->index();
            $table->text('estimation_email_address')->nullable();
            $table->text('photo_report_email_address')->nullable();
            $table->string('company_name')->nullable()->index();
            $table->string('prefecture')->nullable()->index();
            $table->string('city')->nullable()->index();
            $table->string('address')->nullable()->index();
            $table->string('phone1')->nullable()->index();
            $table->string('phone2')->nullable()->index();
            $table->string('fax')->nullable()->index();
            $table->string('incoming_phone')->nullable()->index();
            $table->string('original_incoming_phone')->nullable()->index();
            $table->text('negotiation')->nullable();
            $table->integer('sales')->nullable()->index();
            $table->integer('npair_amount')->nullable()->index();
            $table->string('npair_payment_method')->nullable()->index();
            $table->string('npair_system_registration')->nullable()->index();
            $table->string('npair_credit_result')->nullable()->index();
            $table->string('npair_invoice_issued')->nullable()->index();
            $table->integer('material_cost')->nullable()->index();
            $table->text('material_detail')->nullable();
            $table->integer('material_price')->nullable()->index();
            $table->integer('highway_cost')->nullable()->index();
            $table->string('highway_from')->nullable()->index();
            $table->string('highway_to')->nullable()->index();
            $table->integer('parking_cost')->nullable()->index();
            $table->integer('stamp_cost')->nullable()->index();
            $table->integer('partner_fee')->nullable()->index();
            $table->integer('allowed_cost')->nullable()->index();
            $table->text('allowed_detail')->nullable();
            $table->integer('kurapital_fee')->nullable()->index();
            $table->integer('other_cost')->nullable()->index();
            $table->integer('kurapital_cost')->nullable()->index();
            $table->text('detail')->nullable();
            $table->string('proposal')->nullable()->index();
            $table->integer('kaitori')->nullable()->index();
            $table->string('building_name')->nullable()->index();
            $table->string('shop_name')->nullable()->index();
            $table->integer('requested_lat_lng')->nullable()->index();
            $table->string('last_update_from')->nullable()->index();
            $table->string('building_room')->nullable()->index();
            $table->integer('reception_number')->nullable()->index();
            $table->integer('order_amount')->nullable()->index();
            $table->string('personnel_name')->nullable()->index();
            $table->integer('accounting_confirmed_amount')->nullable()->index();
            $table->integer('basic_research_fee')->nullable()->index();
            $table->integer('budget_amount')->nullable()->index();
            $table->integer('zeroemi_discount')->nullable()->index();
            $table->text('irregular_billing')->nullable();
            $table->integer('houzinflg')->nullable()->index();
            $table->integer('seisanflg')->nullable()->index();
            $table->text('refere')->nullable();
            $table->text('trouble')->nullable();
            $table->text('note')->nullable();
            $table->datetime('order_date')->nullable();
            $table->datetime('receipt_date')->nullable();
            $table->datetime('work_date')->nullable();
            $table->datetime('work_date_end')->nullable();
            $table->datetime('worked_date')->nullable();
            $table->integer('status_id')->nullable();
            $table->integer('sub_status_id')->nullable();
            $table->integer('external_collaboration_status_id')->nullable();
            $table->integer('company_managed_building_id')->nullable();
            $table->integer('account_id')->nullable();
            $table->integer('user_id')->nullable();
            $table->integer('owner_id')->nullable();
            $table->integer('work_content_id')->nullable();
            $table->integer('work_target_id')->nullable();
            $table->integer('cancel_reason_id')->nullable();
            $table->integer('receipt_status_id')->nullable();
            $table->integer('bill_status_id')->nullable();
            $table->integer('opportunity_demand_status_id')->nullable();
            $table->integer('sub_category_id')->nullable();
            $table->integer('shift_id')->nullable();
            $table->integer('on_site_billing_type_id')->nullable();
            $table->integer('on_site_billing_method_id')->nullable();
            $table->integer('tax_rate_id')->nullable();
            $table->integer('sendmail_account_id')->nullable();
            $table->integer('kaiin_flyer_id')->nullable();
            $table->boolean('not_urikake_flg')->nullable()->default(false);
            $table->boolean('work_date_recived')->nullable()->default(false);
            $table->boolean('other_bill_status_id')->nullable()->default(false);
            $table->boolean('pay_by_invoice')->nullable()->default(false);
            $table->boolean('pay_by_service_paper')->nullable()->default(false);
            $table->boolean('payed_by_card')->nullable()->default(false);
            $table->boolean('is_additional_projects')->nullable()->default(false);
            $table->boolean('is_completed')->nullable()->default(false);
            $table->boolean('is_time_designation')->nullable()->default(false);
            $table->boolean('is_reschedule')->nullable()->default(false);
            $table->boolean('is_claim')->nullable()->default(false);
            $table->boolean('is_company')->nullable()->default(false);
            $table->boolean('is_construction')->nullable()->default(false);
            $table->boolean('is_photo_registered')->nullable()->default(false);
            $table->boolean('is_free_time')->nullable()->default(false);
            $table->boolean('is_attendance')->nullable()->default(false);
            $table->boolean('is_accounting_confirmed')->nullable()->default(false);
            $table->boolean('is_transfer')->nullable()->default(false);
            $table->boolean('is_double_window')->nullable()->default(false);
            $table->boolean('is_emittion')->nullable()->default(false);
            $table->boolean('is_irregular_billing')->nullable()->default(false);
            $table->boolean('sendmail')->nullable()->default(false);
            $table->text('cancel')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('opportunities');
    }
};
